version: "3.3"
services:
  interactive-gui:
    image: "python:3.9.17"
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}:/app
    ports:
      - 8501:8501
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MB
    working_dir: /app
    # entrypoint: "streamlit run particles-client.py"
    entrypoint: "streamlit run particle-interactive.py --server.port 8501"
