version: "3.3"
services:
  interactive-gui:
    image: "python:3.8.9"
    volumes:
      - ${PWD}:/app
    ports:
      - 8501:8501
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128MB